version: '3'

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"